name: "Auto backup dnxrg"
version: "1.0.0"
port: 1337
nodes: 
  - game1
  - game2
  - game3
dataDirectory: "./data"
data_file: "data.zip"
token: "SomerandomToken"
BashFile: "./avails/download.sh"
IP_HEADER: "default"
ftp: 
  enabled: true
  uri: "161.97.117.229:21"
  user: "test"
  password: "Rishu@2007"
chunk_size: 4000000