name: "Auto backup dnxrg"
version: "1.0.0"
port: 8888
nodes: 
  - game1
  - game2
  - game3
dataDirectory: "./data"
data_file: "data.zip"
token: "HbEQ0283ew"
BashFile: "./avails/download.sh"
IP_HEADER: "default"
ftp:
  enabled: true
  uri: "172.105.59.152:21"
  user: "backups@dnxrg.net"
  password: "XaQ#P%84V%&q"
chunk_size: 4000000